In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('neet_data.csv')

In [5]:
df

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
0,2020-10-31 14:10:28,141,Twitter for Android,1250294694937915394,Rumi,NaN,14,180,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
1,2020-10-31 14:10:11,1,Twitter for iPhone,57059492,Tom Bewick,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,Sussex,False,https://t.co/w6QEi0PBzP,\xf0\x9f\x91\x87This is a really important iss...,140
2,2020-10-31 14:09:48,141,Twitter Web App,1016022678,Lemonade,"Wisdom is knowing the right path to take, Inte...",285,1013,"Bedfordview, South Africa",False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,2020-10-31 14:09:41,141,Twitter for Android,1085818329816883201,The Rus,NaN,147,467,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
4,2020-10-31 14:09:22,0,Twitter for Android,1227501071490113537,Sakshi Yadav,it's not my attitude it's my style,2,24,NaN,False,NaN,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140
...,...,...,...,...,...,...,...,...,...,...,...,...,...
47376,2020-10-30 15:29:35,0,Twitter for Android,1168840190426632192,neet_fad_do,Bhola sa chora,254,513,NaN,False,NaN,Friend Request \xe2\x9d\x8c\nAcid request \xe2...,56
47377,2020-10-30 15:29:35,1700,Twitter for Android,1696615807,Yarutai - Garbage NEET,Random person who likes drawing (but not a \nl...,23,754,NaN,False,NaN,RT @Telepeturtle: those are some pretty nice s...,74
47378,2020-10-30 15:28:59,167,Twitter for Android,1313330869113745413,Raushan,NaN,2,2,NaN,False,NaN,"RT @KhushnumaKashm1: (8/n)\n18 year old, Basit...",140
47379,2020-10-30 15:28:37,270,Twitter for Android,1161551282995388416,Vijaykant,Finding the enemies of India \xf0\x9f\x87\xae\...,140,1309,NaN,False,NaN,RT @OpIndia_com: Yogi Adityanath asks chief se...,140
47380,2020-10-30 15:28:14,0,Twitter for Android,1211810532006612992,Icarus,404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...,16,45,your friendly local enby,False,NaN,i hate talking to people from my department bu...,139

#### 2. Import CSV and Show Column information and total rows and column

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47381 entries, 0 to 47380
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   created_at           47381 non-null  object
 1   retweet_count        47381 non-null  int64
 2   source               47362 non-null  object
 3   user_id              47381 non-null  int64
 4   user_name            47380 non-null  object
 5   user_description     36510 non-null  object
 6   user_follower_count  47381 non-null  int64
 7   user_friends_count   47381 non-null  int64
 8   user_location        26247 non-null  object
 9   user_verified        47381 non-null  bool
 10  user_url             9280 non-null   object
 11  tweet                47381 non-null  object
 12  length_of_tweet      47381 non-null  int64
dtypes: bool(1), int64(5), object(7)
memory usage: 4.4+ MB

In [9]:
df.shape

(47381, 13)

In [11]:
print(f"Row:{df.shape[0]} and column:{df.shape[1]}")

Row:47381 and column:13

In [12]:
df.shape

(47381, 13)

#### 3. Sort the dataset with highest retweet to low.

In [13]:
df.sort_values(by='retweet_count', ascending=False)

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
32860,2020-11-08 05:30:01,614304,Twitter for iPhone,1024658968394625024,\xe3\x81\xb2\xe3\x81\x88\xe3\x81\xa3,\xe3\x85\xa4\xe3\x82\xa2\xe3\x82\xa4\xe3\x82\x...,62,115,NaN,False,https://t.co/cHZdP4uOdu,"RT @JoeBiden: America, I\xe2\x80\x99m honored ...",140
33262,2020-11-07 21:52:54,581097,Twitter for Android,1099388669448867842,Neet\xf0\x9f\x83\x8fPeet,\xe2\x96\xa0\xe2\x96\xa0\xe2\x96\xa0\xe2\x96\x...,11,141,NaN,False,NaN,"RT @KamalaHarris: We did it, @JoeBiden. https:...",63
35111,2020-11-06 14:20:33,381458,Twitter Web App,2578241503,\xe3\x81\xaf\xe3\x81\xaa\xe3\x81\x91\xe3\x81\x...,Kei|20\xe2\x86\x91|intp|eng/fil OK|SparQlew\xe...,624,527,read carrd before follow!!,False,https://t.co/XgmHbPUgAi,RT @GretaThunberg: So ridiculous. Donald must ...,140
32585,2020-11-08 07:19:02,204348,Twitter for iPhone,1103362192169189376,Parneet kaur,"\xf0\x9f\x96\x95 all negative , all positive v...",587,193,"New Jersey, USA",False,https://t.co/PXgYJf0gIA,RT @Al_Sanchino: It\xe2\x80\x99s wild Trump su...,140
38044,2020-11-04 18:19:13,192350,Twitter for iPhone,54249914,Couture_Neet,snapchat . Neetsobeautiful,547,1182,Miii Casaa,False,NaN,"RT @JoeBiden: Keep the faith, guys. We\xe2\x80...",57
...,...,...,...,...,...,...,...,...,...,...,...,...,...
33534,2020-11-07 16:45:39,0,Twitter Web App,1301196667887038464,\xe0\xae\xaa\xe0\xae\xbe\xe0\xae\x9c\xe0\xae\x...,"Indian,BJP supporter",11,37,Tirunelveli,False,NaN,@mosquitomani @vishnuuparam @onandi143 When Bj...,140
33533,2020-11-07 16:46:12,0,Twitter for iPhone,2835488103,Praise be to Hibiki (Thanks be to Symphogear),Blessed be the name of Hibiki\nBuilt a new DnD...,1324,4252,Ha ha! Time for ethics!,False,NaN,@FallerHunter03 @icypika @ooo_thank @HerShinin...,140
13611,2020-10-27 01:23:03,0,Twitter for Android,1207560622273159169,sochkpostkaro,Janta ki awaz uthayenge,24,164,NaN,False,NaN,@Imritik_ @Swamy39 @theicai Galat insan ko tag...,140
33531,2020-11-07 16:48:10,0,Twitter for Android,905021614546313216,Indore Talk,Indore Talk is City's First Hyperlocal Infotai...,5031,25,"Indore, India",False,https://t.co/41cPZozsD8,#FeaturedTalk: Prepare with the Subject Expert...,140
47380,2020-10-30 15:28:14,0,Twitter for Android,1211810532006612992,Icarus,404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...,16,45,your friendly local enby,False,NaN,i hate talking to people from my department bu...,139

#### 4. Show the tweet source, count,  user_name, tweet, created_at and user_url highest value of retweet count.