In [ ]:
import pandas as pd

In [ ]:
df= pd.read_excel('Data_Train.xlsx')
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [ ]:
df.Airline.value_counts()

Airline
Jet Airways                          3849
IndiGo                               2053
Air India                            1752
Multiple carriers                    1196
SpiceJet                              818
Vistara                               479
Air Asia                              319
GoAir                                 194
Multiple carriers Premium economy      13
Jet Airways Business                    6
Vistara Premium economy                 3
Trujet                                  1
Name: count, dtype: int64

In [ ]:
# pip install scikit-learn

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
encoder= LabelEncoder()

In [ ]:
encoder.fit(df.loc[:,'Airline'])

LabelEncoder()

In [ ]:
val=encoder.transform(df.loc[:,'Airline'])
val

array([ 3,  1,  4, ...,  4, 10,  1])

In [ ]:
df.insert(1, column='new', value=val)

In [ ]:
df.head(10)

,Airline,new,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,3,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,4,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,3,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,3,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
5,SpiceJet,8,24/06/2019,Kolkata,Banglore,CCU → BLR,09:00,11:25,2h 25m,non-stop,No info,3873
6,Jet Airways,4,12/03/2019,Banglore,New Delhi,BLR → BOM → DEL,18:55,10:25 13 Mar,15h 30m,1 stop,In-flight meal not included,11087
7,Jet Airways,4,01/03/2019,Banglore,New Delhi,BLR → BOM → DEL,08:00,05:05 02 Mar,21h 5m,1 stop,No info,22270
8,Jet Airways,4,12/03/2019,Banglore,New Delhi,BLR → BOM → DEL,08:55,10:25 13 Mar,25h 30m,1 stop,In-flight meal not included,11087
9,Multiple carriers,6,27/05/2019,Delhi,Cochin,DEL → BOM → COK,11:25,19:15,7h 50m,1 stop,No info,8625

In [ ]:
df.loc[:,'Airline'].value_counts()

Airline
Jet Airways                          3849
IndiGo                               2053
Air India                            1752
Multiple carriers                    1196
SpiceJet                              818
Vistara                               479
Air Asia                              319
GoAir                                 194
Multiple carriers Premium economy      13
Jet Airways Business                    6
Vistara Premium economy                 3
Trujet                                  1
Name: count, dtype: int64

In [ ]:
df.loc[:,'new'].value_counts()

new
4     3849
3     2053
1     1752
6     1196
8      818
10     479
0      319
2      194
7       13
5        6
11       3
9        1
Name: count, dtype: int64

In [ ]:
# One hot encoder

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
enc= OneHotEncoder()

In [ ]:
df.loc[:,'Source'].value_counts()

Source
Delhi       4537
Kolkata     2871
Banglore    2197
Mumbai       697
Chennai      381
Name: count, dtype: int64

In [ ]:
df.loc[:,['Source']]

         Source
0      Banglore
1       Kolkata
2         Delhi
3       Kolkata
4      Banglore
...         ...
10678   Kolkata
10679   Kolkata
10680  Banglore
10681  Banglore
10682     Delhi

[10683 rows x 1 columns]

In [ ]:
var= enc.fit_transform(df.loc[:,['Source']])   # accepts 2d data means dataframe

In [ ]:
var.toarray()

array([[1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       ...,
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [ ]:
feature= enc.get_feature_names_out()
feature

array(['Source_Banglore', 'Source_Chennai', 'Source_Delhi',
       'Source_Kolkata', 'Source_Mumbai'], dtype=object)

In [ ]:
df.loc[:,feature]= var.toarray()

In [ ]:
df.head(3)

,Airline,new,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Source_Banglore,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai
0,IndiGo,3,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,1.0,0.0,0.0,0.0,0.0
1,Air India,1,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,0.0,0.0,0.0,1.0,0.0
2,Jet Airways,4,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,0.0,0.0,1.0,0.0,0.0

In [ ]:
df.Destination.value_counts()

Destination
Cochin       4537
Banglore     2871
Delhi        1265
New Delhi     932
Hyderabad     697
Kolkata       381
Name: count, dtype: int64

In [ ]:
pd.get_dummies(df.loc[:,'Destination'])

       Banglore  Cochin  Delhi  Hyderabad  Kolkata  New Delhi
0         False   False  False      False    False       True
1          True   False  False      False    False      False
2         False    True  False      False    False      False
3          True   False  False      False    False      False
4         False   False  False      False    False       True
...         ...     ...    ...        ...      ...        ...
10678      True   False  False      False    False      False
10679      True   False  False      False    False      False
10680     False   False   True      False    False      False
10681     False   False  False      False    False       True
10682     False    True  False      False    False      False

[10683 rows x 6 columns]

In [ ]:
df.Total_Stops.value_counts()

Total_Stops
1 stop      5625
non-stop    3491
2 stops     1520
3 stops       45
4 stops        1
Name: count, dtype: int64

In [ ]:
df.Total_Stops.map({'1 stop':0,'non-stop':1,'2 stops':2,'3 stops':3,'4 stops':4})

0        1.0
1        2.0
2        2.0
3        0.0
4        0.0
        ...
10678    1.0
10679    1.0
10680    1.0
10681    1.0
10682    2.0
Name: Total_Stops, Length: 10683, dtype: float64